{{- if .Values.addons.metricsServer.enabled  }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: metrics
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.addons.metricsServer.git.repo }}
  ref:
    {{- include "validRef" .Values.addons.metricsServer.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" . | nindent 2 }}
{{- end }}
